### ISSUE TITLE
add topic quantum-chemistry

### ISSUE THREAD

**Issue by Beliavsky** [1234zou/MOKIT#1]
I suggest adding the topic quantum-chemistry in the About section. I have added the project to the category Quantum Chemistry and Electronic Structure in a [list of Fortran codes](https://github.com/Beliavsky/Fortran-code-on-GitHub) I maintain.

**Comment by 1234zou** [comment]
@Beliavsky Thanks. The About section has been updated.

**Comment by Beliavsky** [comment]
No, it should like https://github.com/cp2k/cp2k for example, where there are 4 topics listed. See https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/classifying-your-repository-with-topics .

**Comment by 1234zou** [comment]
Oh, I see. It should be O.K. now.
