### ISSUE TITLE
[BUG] using non-default program for calculation

### ISSUE THREAD

**Issue by wangdu817** [1234zou/MOKIT#3]
两个BUG：
1个是用Gaussian做GVB时，会报错
IDnsty.ne.1 in pure raf dig.
 Error termination via Lnk1e in /share/home/wd/g16/l506.exe at Fri Nov 17 16:38:39 2023.

另一个是用molpro做casscf的时候找不到能量的关键词:
ERROR in subroutine read_cas_energy_from_molpro_out: 'ITER. M' not found in file C5H9NO_rhf_gvb17_CASSCF.out

下边是molpro的能连关键词：
 **********************************************************************************************************************************

 CASSCF/USERDEF energy=   -324.051188644457

          CASSCF
   -324.05118864
 **********************************************************************************************************************************
 Molpro calculation terminated

**Comment by 1234zou** [comment]
当前信息过少。能否上传你计算报错的输入、输出文件？最好是打包压缩一下。另外，你用的MOKIT版本是什么？
（因为我随便找个例子来算，`GVB_prog=Gaussian`和`CASSCF_prog=Molpro`都很正常，因此需要你那里的更多信息来排查）

**Comment by wangdu817** [comment]
我是从帮助文档里下载的conda Py39 linux离线安装版本，抱歉错误信息没有保存，我后来采用默认的pyscf 和gamess做CASSCF和GVB就可以正常运行了，不过最后用molpro做caspt2仍然提示找不到关键词，附件是mokit out和molpro out文件
[log.zip](https://github.com/1234zou/MOKIT/files/13400682/log.zip)

**Comment by 1234zou** [comment]
原因是Molpro 2022的输出格式发生了微小变化，请下载目前最新版v1.2.6rc17使用，此问题已修复。
