### ISSUE TITLE
gaussview6 无法查看mokit生成的fch轨道文件

### ISSUE THREAD

**Issue by wangdu817** [1234zou/MOKIT#4]
![image](https://github.com/1234zou/MOKIT/assets/44027514/c99e12d2-fbff-47de-856d-f05920233005)
直接双击是这样的，这个好像是因为chk是g09的格式，我把line40的MM charges 改成了 MM charge 并且把后边的charge数量改成N=0就正常打开了。但是利用guassian16计算cube时候还是会报错，无法生成等值面，如下图。文件包中是修改后的fch文件
![image](https://github.com/1234zou/MOKIT/assets/44027514/fd7159b1-f5fb-4b9f-a06b-e9b21016375d)
[C5H9NO_rhf_gvb17_CASSCF_NO.zip](https://github.com/1234zou/MOKIT/files/13512777/C5H9NO_rhf_gvb17_CASSCF_NO.zip)

**Comment by jeanwsr** [comment]
我平常的CASSCF任务产生的fch是可以打开的。可以上传未修改的fch文件吗？

**Comment by 1234zou** [comment]
这跟MOKIT没什么关系，应该是你在计算过程中混用了g09/g16，例如使用g09的formchk去操作g16的chk文件，产生的fch文件里面MM charges部分就是异常的数值。

至于哪里混用了g09/g16，有两种可能：
（1）你的环境变量里同时有g09和g16生效，这不仅可能导致你自己混用g09/g16，也可能导致`automr`混用g09/g16，急需阅读此文[《G16和G09环境变量同时生效的危害》](https://mp.weixin.qq.com/s/HmUST3mqsy659ZPyJoIP6g)。
（2）你通过readrhf/readuhf/readno关键词提供给`automr`一个fch文件，这个fch文件是有问题的，这个问题在计算中被继承了下来。

**Comment by 1234zou** [comment]
I'm closing this issue since there is no further question or reply.
