### ISSUE TITLE
Import Error in py2fch when compiling from source on linux and installing with homebrew

### ISSUE THREAD

**Issue by lmhuntin** [1234zou/MOKIT#7]
I tried to install MOKit in 2 different ways (compiling from source (latest stable version) on a linux machine and using homebrew on my mac) and I run into the same problem in both cases when trying to run the example `07-OH_writefch.py`. Namely, I obtain the following import error

```
Traceback (most recent call last):
  File "/Users/lee.huntington/test_orbitals/07-OH_writefch.py", line 8, in <module>
    from mokit.lib.py2fch_direct import fchk
  File "/opt/homebrew/opt/mokit/mokit/lib/py2fch_direct.py", line 1, in <module>
    from mokit.lib.py2fch import molinfo2fch, molecp2fch, py2fch
ModuleNotFoundError: No module named 'mokit.lib.py2fch'
```

 I have made sure to put the recommended export statements in the corresponding bashrc or zshrc file in each case. The `PYTHONPATH` points to the MOKit directory. Am I doing something wrong or is there an issue with the code?

**Comment by 1234zou** [comment]
Hi, I'm more familiar with compiling MOKIT in Linux, maybe we can talk about problems in Linux firstly?

If you are sure that your environment variables are reasonable, there is one possible problem which users often encounter:
the Python version and environment should be kept identical when compiling MOKIT and when using MOKIT.

For example, if you compile MOKIT in a python-3.9 env and you exit as well as re-login, forget to activate/load the python-3.9 env, but use MOKIT in a python-3.8 env. Then `ModuleNotFoundError` error usually occurs. To check if it is such case, you can run
```
which python
python --version
ls $MOKIT_ROOT/mokit/lib/py2fch*.so
```
to see whether the python versions are consistent. For example,
```
py2fch.cpython-311-x86_64-linux-gnu.so
```
means it is compiled in a python-3.11 environment. Thus `python --version` is supposed to be also 3.11.

**Comment by lmhuntin** [comment]
Thanks so much! Much appreciated! That's what the issue was. Sorry to bother you.
