### ISSUE TITLE
使用molden2fch小程序时报错

### ISSUE THREAD

**Issue by Doraemon011099** [1234zou/MOKIT#8]
输入molden2fch 10a-cas.molden -molpro 后报错，报错信息见下图：
![error1](https://github.com/user-attachments/assets/38a181bf-8507-41b0-a7b4-4658fc5373a8)
![error2](https://github.com/user-attachments/assets/9403b492-bb56-4085-841b-cdd1a0b16b09)
[10a-cas_moldenfile.zip](https://github.com/user-attachments/files/17647581/10a-cas_moldenfile.zip)

**Comment by 1234zou** [comment]
I'm sorry that this is a bug for MOKIT-v1.2.6rc37 ~ 1.2.6rc41. It will be fixed in 1.2.6rc42. You can either wait for the update of 1.2.6rc42, or use the following workaround immediately
```
conda create -n mokit-py39 python=3.9
conda activate mokit-py39
conda install mokit=1.2.6rc35 -c mokit
molden2fch 10a-cas.molden -molpro
```

**Comment by Doraemon011099** [comment]
Thank you for your response and all the help provided. The issue has been resolved!

**Comment by 1234zou** [comment]
MOKIT-v1.2.6rc42 has been updated. This issue is solved. You can re-open it if you have any further question.
